name: Generate Datas
on:
  schedule:
    - cron: "0 */12 * * *" # executa a cada 12h na hora cheia
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Snake Animation
      - uses: Platane/snk@v3
        with:
          github_user_name: VitorFidelis
          outputs: |
            dist/github-contribution-grid-snake.svg
          colors: |
            background:#1C1C1C
            snake:#F8F8FF

      # Publica no branch "output"
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
